trainer:
  batch_size: 16
  val_batch_size: 16
  test_batch_size: 64
  max_epochs: 200
  class_start: 0
  class_end: 5
  k_shot: 20
  encoder: "AlexNet"
  freeze: True
  pretrain: True
  pretrained_path: "../pretext/_experiments/Rot_Predict_AlexNet/feature_net_epoch245"

optimizer:
  params:
    lr_encoder: 0.001
    lr_classifier: 0.001
    weight_decay: 0

iteration: 10

num_class: 6

dataset_root: "../../dataset/WiFi_ft62/"
